// Code generated by mdatagen. DO NOT EDIT.

package metadata

import "go.opentelemetry.io/collector/confmap"

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for zipkin_udp metrics.
type MetricsConfig struct {
	ReceiverZipkinUDPCountBufferFull         MetricConfig `mapstructure:"receiver_zipkin_udp_count_buffer_full"`
	ReceiverZipkinUDPCountSpansDropped       MetricConfig `mapstructure:"receiver_zipkin_udp_count_spans_dropped"`
	ReceiverZipkinUDPCountSpansFailedToParse MetricConfig `mapstructure:"receiver_zipkin_udp_count_spans_failed_to_parse"`
	ReceiverZipkinUDPCountSpansReceived      MetricConfig `mapstructure:"receiver_zipkin_udp_count_spans_received"`
	ReceiverZipkinUDPCountUDPOverflows       MetricConfig `mapstructure:"receiver_zipkin_udp_count_udp_overflows"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		ReceiverZipkinUDPCountBufferFull: MetricConfig{
			Enabled: true,
		},
		ReceiverZipkinUDPCountSpansDropped: MetricConfig{
			Enabled: true,
		},
		ReceiverZipkinUDPCountSpansFailedToParse: MetricConfig{
			Enabled: true,
		},
		ReceiverZipkinUDPCountSpansReceived: MetricConfig{
			Enabled: true,
		},
		ReceiverZipkinUDPCountUDPOverflows: MetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for zipkin_udp metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}
